services:
  db:
    image: mysql:5.7.2
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=db_dev  # Requested, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - rct_mysql_data:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.
    networks:
      - seafile-net
    deploy:
      resources:
        limits:
          memory: 100M

  memcached:
    image: memcached:1.5.6
    container_name: seafile-memcached
    entrypoint: memcached -m 16
    networks:
      - seafile-net
    deploy:
      resources:
        limits:
          memory: 16M

  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    ports:
      - "80:80"
      - "8000:8000"
      - "8082:8082"
#      - "443:443"  # If https is enabled, cancel the comment.
    volumes:
      - rct_cloud_data:/shared   # Requested, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=db_dev  # Requested, the value shuold be root's password of MySQL service.
#      - TIME_ZONE=Asia/Shanghai # Optional, default is UTC. Should be uncomment and set to your local time zone.
      - SEAFILE_SERVER_HOSTNAME=cloud.transformers.science
      - SEAFILE_ADMIN_EMAIL=tsinghua9boy@sina.com
      - SEAFILE_ADMIN_PASSWORD=rct123
      - SEAFILE_SERVER_LETSENCRYPT=false   # Whether use letsencrypt to generate cert.
    restart: always
    depends_on:
      - db
      - memcached
    networks:
      - seafile-net
    deploy:
      resources:
        limits:
          memory: 200M

volumes:
  rct_mysql_data:
  rct_cloud_data:


networks:
  seafile-net:
    external: false
    driver: bridge